#### Import all libraries

In [1]:
from __future__ import print_function
import os
import collections
import SimpleITK as sitk
import numpy as np
import six
import radiomics
from radiomics import firstorder, glcm, imageoperations, shape, glrlm, glszm, getTestCase
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import nrrd
from pathlib import Path
import sys
import logging as logger
import time
import json
import os
import logging.config
import pandas as pd
import gc

In [2]:
#Read the entire Benthiemer sandstone
global image_1, label_1
filename_ben = 'investigate_bent_8bit.nrrd'
image_1 = sitk.ReadImage('C:\\Users\\User\\Desktop\\WRR\\pyradiomics\\data\\investigate_bent_8bit.nrrd')

#### Extraction Settings

In [3]:
settings = {}
settings['label'] = 255

In [4]:
%%time
ultimate_mask = np.zeros((4, 4, 4))
global window_size, total_iter, expect_iter, i_loc, j_loc, z_loc, bb, correctedMask, croppedImage, croppedMask, glcm_window
for window_size in range(2,5,1):
    expect_iter = (ultimate_mask.shape[1] - window_size + 1)**3
    print("Expected Calculations for Window", str(window_size), ". The expected of iterations is ", str(expect_iter))        
    glcm_window = np.zeros((expect_iter,1))
    total_iter = 0
    for i_loc in range(ultimate_mask.shape[0]-window_size+1):
        for j_loc in range(ultimate_mask.shape[1]-window_size+1):
            for z_loc in range(ultimate_mask.shape[2]-window_size+1):           
                full_mask = np.zeros((4, 4, 4), dtype = np.uint8)
                full_mask[i_loc:i_loc+window_size,j_loc:j_loc+window_size,z_loc:z_loc+window_size] = 255
                print(full_mask)
                

Expected Calculations for Window 2 . The expected of iterations is  27
[[[255 255   0   0]
  [255 255   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[255 255   0   0]
  [255 255   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]]
[[[  0 255 255   0]
  [  0 255 255   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0 255 255   0]
  [  0 255 255   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]]
[[[  0   0 255 255]
  [  0   0 255 255]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0 255 255]
  [  0   0 255 255]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0 